### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by rwv37** [glujan/drpg#143]
Recently (I think the day before yesterday, but I'm not 100% sure), I started getting:
```
HTTP Request: POST https://www.drivethrurpg.com/api/v1/token?fields=customers_id "HTTP/1.1 503 Service Temporarily Unavailable"
Unexpected error occurred, stopping!
```
This happens every time, and it happens more or less immediately. At first I thought "OK, temporarily unavailable, I'll wait and try again", but I've been doing so over the course of days, and I'm beginning to worry that "temporarily unavailable" might mean "permanently unavailable", or perhaps "temporarily unavailable until DTRPG notices something's going wrong" (which, in terms of practical effect, might be the same thing).

I have turned on debug logging, but it doesn't seem to provide much more of a clue in this case:
```
load_ssl_context verify=True cert=None trust_env=True http2=False
load_verify_locations cafile='/home/bob/.local/lib/python3.11/site-packages/certifi/cacert.pem'
connect_tcp.started host='www.drivethrurpg.com' port=443 local_address=None timeout=30.0 socket_options=None
connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0xd14e39fecd0>
start_tls.started ssl_context=<ssl.SSLContext object at 0xd14e393df40> server_hostname='www.drivethrurpg.com' timeout=30.0
start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0xd14e39f8450>
send_request_headers.started request=<Request [b'POST']>
send_request_headers.complete
send_request_body.started request=<Request [b'POST']>
send_request_body.complete
receive_response_headers.started request=<Request [b'POST']>
response_closed.started
response_closed.complete
Unexpected error occurred, stopping!
Traceback (most recent call last):
  File "/home/bob/.local/bin/drpg", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/cmd.py", line 32, in run
    DrpgSync(config).sync()
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/sync.py", line 60, in sync
    self._api.token()
  File "/home/bob/.local/lib/python3.11/site-packages/drpg/api.py", line 69, in token
    login_data = resp.json()["message"]
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Is this happening to anyone else? Is there something else I can try, or further troubleshooting info I can look at and/or provide?

Thanks in advance.

**Comment by glujan** [comment]
I'm afraid this is rate limiting. DriveThruRPG uses CloudFlare: https://community.cloudflare.com/t/community-tip-fixing-error-503-service-unavailable-service-temporarily-unavailable/44438

**Comment by rwv37** [comment]
Thanks. Do you know if this is something that would be hitting DTRPG's API in general, or perhaps more targeted to me due to using it too much?

**Comment by rwv37** [comment]
I should probably say that I can use their website (as opposed to the API).

**Comment by glujan** [comment]
Maybe there is something I can do about it for drpg.

When I originally developed drpg, DriveThruRPG was not using Cloudflare - or it wasn't configured to include throttling, or users weren't noticing it is configured because of fewer CPU cores on users PCs back then. I would need to see again how their official client handles it.

The flow for downloading a product is something like:
1. Ask the DriveThruRPG API to generate a signed download link. Drpg gets the link instantly, but the link may not be ready yet.
2. Poll their API to see if the download link is ready.
3. Use the download link to fetch the product. It points to their CDN (Cloudflare based, or at least Cloudflare protected).

To speed things up, drpg is multi threaded - it generates download links and downloads multiple products at once. The number of threads is based on the user's CPU core counts.

There are a few things I can think of that can be tried out:
- lower number of threads,
- download products from CDN one by one,
- look at response headers - maybe their API includes information about rate - limiting.

**Comment by niclasmagnusson** [comment]
> I should probably say that I can use their website (as opposed to the API).

I have this same issue with drpg, and I can use their website as normal. I also yesterday downloaded their horrible Windows-client, and got everything downloaded through it. Just wanted to share that if that would be of any use in this.

**Comment by bschollnick** [comment]
I would think that If the official client is working, then in theory, we could sniff the traffic from the official client, and reverse engineer the process it's getting around the rate limiting from cloud flare...

**Comment by rwv37** [comment]
Would it perhaps be possible, at least as an interim workaround, to have a version that can be configured to not multithread?

**Comment by glujan** [comment]
> Would it perhaps be possible, at least as an interim workaround, to have a version that can be configured to not multithread?

My guess was bad, they simply turned off their old API.

But I have good news - I was able to set up mitmproxy with the official client, installed on my Linux box via wine! I captured the requests and may be able to bring drpg back to life 🤞

**Comment by glujan** [comment]
Please update drpg, I've just uploaded version 2024.12.19 which uses the new API.

If the new version does not work for you, please open a new issue. Thank you!

**Comment by xmagnn** [comment]
Do I need to do anything more then pip install -U drpg ? I still get the same error

**Comment by bschollnick** [comment]
Try again….  I had the same issue, it appears to take some time before the new release “percolates” through PyPI and/or Github.  

I just tried a few moments ago, and it updated and works fine…  Currently running through my list of DriveThru RPG files…

	- Benjamin

**Comment by rwv37** [comment]
Thanks so much! It seemed to work fine for me.

**Comment by rwv37** [comment]
> Do I need to do anything more then pip install -U drpg ? I still get the same error

@xmagnn What I did (and which worked fine) was:
```pip install --upgrade --user drpg```
I see that your ``-U`` is equivalent to my ``--upgrade``, so maybe the issue is that you originally installed it for the user, and the "upgrade" (without specifying ``--user`` actually installed (or upgraded) it for the world? Then when you ran it again, it used the (unupgraded) user's version?

I'm not really familiar with ``pip``, so I don't know that this is the way it would work; just a stab-in-the-dark guess.

**Comment by rwv37** [comment]
> And yes, `-U` and `--user` are equivalents.

That's ``-U`` and ``--upgrade``, right?

**Comment by glujan** [comment]
> > And yes, `-U` and `--user` are equivalents.
> 
> That's ``-U`` and ``--upgrade``, right?

Yes, my bad. I edited the previous comment, thanks for spotting this!

**Comment by xmagnn** [comment]
> I see that your `-U` is equivalent to my `--upgrade`, so maybe the issue is that you originally installed it for the user, and the "upgrade" (without specifying `--user`) actually installed (or upgraded) it for the world? Then when you ran it again, it used the (unupgraded) user's version?

That was exactly the case, the user had the updated drpg-file, but I also had a ~/.local/bin/drpg which was the old version and that was the one in the path. I assume I have installed it both for my user and systemwide. I'll sort it out somehow, but now it's running.
