### ISSUE TITLE
Fails on Linux due to "/" in folder name

### ISSUE THREAD

**Issue by cas206** [glujan/drpg#2]
Processing: /r/dndbehindthescreen Monster Ecology Anthology - 893096-Monster_ecology_anthology.pdf
Waiting to download: 207419 - 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/pathlib.py", line 1279, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/r/dndbehindthescreen Monster Ecology Anthology'

**Comment by glujan** [comment]
Thanks for the report. I'll fix that later today!

**Comment by glujan** [comment]
@cas206 Could you try running the script using `fix/escape-folder-name` branch?

**Comment by glujan** [comment]
I found that product on DriveThroughRPG, added it to my account and it syncs with a fix I prepared.
